# Generated by Django 3.2.19 on 2024-02-28 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0002_tasklist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='user',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
